### ISSUE TITLE
Allow binding to multiple keys/buttons

### ISSUE THREAD

**Issue by vheuken** [panzi/qjoypad#13]
I'd like to bind a gamepad button to two different gamepad buttons. Specifically, I'd like Button 6 to be bound to Buttons 1 and 3 so that pressing Button 6 behaves the same as pressing buttons 1 and 3 simultaneously. Is this within the scope of the project?

**Comment by panzi** [comment]
Sorry, this is indeed not in the scope of this project. At this point it is basically in maintenance only mode. I'm not sure, but maybe [AntiMicro](https://github.com/AntiMicro/antimicro) supports this feature?

**Comment by vheuken** [comment]
@panzi I was able to bind gamepad buttons to multiple keyboard inputs through AntiMicro. I should see if they're open to supporting binding to gamepad buttons. Thanks!
