### ISSUE TITLE
QT from 5.12.4 to 5.13.0 compilation fails

### ISSUE THREAD

**Issue by substring** [panzi/qjoypad#24]
Hi,

This version of QT produces many errors `error: ‘QString::null’ is deprecated: use QString()`

**Comment by substring** [comment]
later complains with `error: ‘const QBrush& QPalette::background() const’ is deprecated: Use QPalette::window()`

**Comment by panzi** [comment]
Thank you for the report.
I'm, as always, on an outdated Linux distribution. If you can fix those errors and send a pull request that would be awesome! :D

**Comment by substring** [comment]
Sure I can as soon as I'm done testing it. Then you'd need to test it on an older version of QT, but looks like it's no problem for you :smile:

Thank you for the quick feedback :wink:

**Comment by panzi** [comment]
Works with Qt 5.11.3
Thank you! :D

**Comment by substring** [comment]
Nice, you're welcome :smiley: 
Could you consider releasing 4.3.1 ?

**Comment by panzi** [comment]
done https://github.com/panzi/qjoypad/releases/tag/v4.3.1 :D
