### ISSUE TITLE
Does not recognize Nintendo Nunchuk or directional pad

### ISSUE THREAD

**Issue by joshop** [panzi/qjoypad#26]
Qjoypad is able to recognize a Nintendo Wiimote and Classic Controller without issue but fails to recognize a Nunchuk. It simply displays the device as one joystick and the list of buttons does not change when the nunchuk is used. Also, the directional pads on both the Wiimote and a classic controller are not recognized as buttons or axes.

**Comment by panzi** [comment]
That's more of an issue with the Linux driver than with qjoypad. I for one haven't managed to get any Bluetooth gamepads to work at all under Linux. :/

**Comment by joshop** [comment]
Hmm. Other tools (cwiid) have been able to recognize the Nunchuk C and Z keys but were unable to control the mouse and thus were unsuitable, and, as I said, the Wiimote by itself works fine. Are there any drivers that I could install that would allow the Nunchuk to be used?

**Comment by panzi** [comment]
cwiid implements it's own Wii remote driver on top of the Bluetooth API. I use the Linux gamepad API (`linux/joystick.h`) and thus depend on Linux kernel drivers for gamepad support. I won't implement any special purpose code for a gamepad I can't even test. You need to report a bug to the Linux kernel driver for the Wii remote (xwiimote).
