### ISSUE TITLE
not able to run qjoypad without xserver - qjoypad in commandline

### ISSUE THREAD

**Issue by Schlumpf7** [panzi/qjoypad#45]
Hi there,
i want to run qjoypad in commandline without xserver running.
it just says:
qjoypad: cannot connect to X server
Is there a way to run it without it?
Best regards 
Schlumpf7

**Comment by panzi** [comment]
Nope, sorry. This is a Qt application.

**Comment by panzi** [comment]
PS: It wouldn't make sense at all anyway, because the whole purpose of this program is to send emulated mouse and keyboard events to the X11 server.
