### ISSUE TITLE
[Feature] Add ability to switch layouts via joystick buttons

### ISSUE THREAD

**Issue by Robbi-Blechdose** [panzi/qjoypad#55]
I have a Saitek X52, which has a wheel with 3 buttons for selecting "profiles" with the original windows software.
These profiles are much like the layouts in QJoyPad.
Adding the option to map joystick buttons to layout changes should replicate the original functionality quite well.
Is this something that would benefit QJoyPad?

**Comment by panzi** [comment]
Yes that feature would make sense, but I don't have time or energy to implement it. Also don't have such a gamepad (still only an Xbox 360 gamepad), so I couldn't test it. Don't know as what that wheel is recognized (buttons or axis).

**Comment by Robbi-Blechdose** [comment]
The wheel is recognized as 3 buttons, and one is permanently "pressed". That means layout changes should only be done when the button is pressed down (change) instead of repeatedly.
I believe the feature could still be tested using normal buttons.
Would you welcome a pull request for this?
