### ISSUE TITLE
Qt5 port

### ISSUE THREAD

**Issue by akien-mga** [panzi/qjoypad#6]
Hi there,

I just took over the maintainership of the qjoypad package for Mageia, and happily found out about your fork when looking for more recent versions than 4.1.0. I just finished packaging it and it works like a charm, so thank you! :)

Have you considered porting QJoyPad to Qt5? I've worked on porting a few apps from Qt4 to Qt5 and it's usually relatively painless, so I could also help working on it for qjoypad if you'll be around to merge PRs :)

**Comment by panzi** [comment]
Well, yes. Except I'm currently on a quite outdated Linux installation. Will upgrade over Christmas or so and then I can look at Qt5.

**Comment by panzi** [comment]
Ok, "ported" it to Qt 5. All I had to do is to change the `CMakeLists.txt` files and a workaround for a conflict between `Xlib.h` and Qt 5.
