### ISSUE TITLE
Internationalization produces broken layout files

### ISSUE THREAD

**Issue by akien-mga** [panzi/qjoypad#8]
As reported by @doktor5000 on https://bugs.mageia.org/show_bug.cgi?id=17306#c2, it looks like the use of the German translation in QJoypad 4.2.0 produces broken layout files, as the translated names are used in it:

```
$ cat ~/.qjoypad3/test.lyt

# QJoyPad 4.2 Layout File

Joystick 1 {
        Achse 1: +key 0, -key 0
        Achse 2: +key 0, -key 0
        Achse 3: +key 0, -key 0
        Achse 4: +key 0, -key 0
        Achse 5: +key 0, -key 0
        Achse 6: +key 0, -key 0
        Taste 1: key 38
        Taste 2: key 53
        Taste 3: key 0
        Taste 4: key 0
        Taste 5: key 0
        Taste 6: key 0
        Taste 7: key 0
        Taste 8: key 0
        Taste 9: key 0
        Taste 10: key 0
        Taste 11: key 0
        Taste 12: key 0
}
```

which triggers this error upon load:
```
/dev/input: keybinding file failure
Error while reading layout. Unrecognized word: achse
```

It appears to be a regression as 4.1.0 had no translation support.

**Comment by akien-mga** [comment]
On a side note, he also noted that version 4.1.0 used to save only the settings for keys that had actually been modified, while 4.2.0 seems to save all keys, assigning non-custom ones to key 0.
See:
```
$ cat ~/.qjoypad3/test.lyt 
# QJoyPad 4.1 Layout File

Joystick 1 {
        Button 1: key 38
        Button 2: key 53
}
```
for the same configuration as above. It's not a bug per se, but if it's not a conscious change, it might be work looking into to prevent saving non-relevant info in the layout file.

**Comment by akien-mga** [comment]
Note that there are a couple other issues in the bug report linked above, we might open some more tickets once they're better diagnosed.

**Comment by panzi** [comment]
Oh, wow. That's quite a stupid bug, sorry. I'll look into it when I have time.

**Comment by panzi** [comment]
About:

>  it doesn't show the name of my gamepad, it only shows "Joysticks: 1".
> E.g. systemsettings shows "Logitech Logitech RumblePad 2 USB (/dev/input/js0)"

In the qjoypad window it shows the gamepad name, but in the tray menu it only shows a list of gamepad numbers. That probably doesn't make any sense whatsoever and should just be removed (or replaced with the number of gamepads connected). I have no idea what I was thinking there. I'll remove it.

**Comment by panzi** [comment]
Even though I didn't have time I fixed it.

**Comment by akien-mga** [comment]
Awesome, thanks. I'll package it and we'll test the new version thoroughly too :)
